Feature/redux
RinatKhabibullin/task-manager pull request #26
Opened 2021-05-13 14:31 UTC by RinatKhabibullin

2021-05-14 07:53 UTC, Ensaphelon commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +  useEffect(() => {
useEffect(loadBoard, [])

2021-05-14 07:53 UTC, Ensaphelon commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +  const handleOpenAddPopup = () => {
`handle{Object}{Action}` -> `handleAddPopupOpen`

check it everywhere

2021-05-14 07:53 UTC, Ensaphelon commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +      return null;
`return` is enough

2021-05-14 07:53 UTC, Ensaphelon commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +    const attributes = TaskForm.attributesToSubmit(params);
`TaskForm.serialize(params)`

2021-05-14 07:53 UTC, Ensaphelon commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +    const attributes = TaskForm.attributesToSubmit(task);
same here

2021-05-14 07:53 UTC, Ensaphelon commented on app/javascript/slices/TasksSlice.js
> +      q: { stateEq: state },
query params should come from the component.

2021-05-14 07:53 UTC, Ensaphelon commented on app/javascript/slices/TasksSlice.js
> +      perPage,
same here

2021-05-17 15:53 UTC, Ensaphelon requested changes

2021-05-17 15:53 UTC, Ensaphelon commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +  const { board, loadBoard, loadColumn, loadColumnMore, queryParamsCreate } = useTasks();
1. Функция, возвращающая параметры запроса не должна возвращаться из хука. Нужно реализовать через экспорт/импорт.
2. queryParamsCreate - не самое лучше название. По русски это должно звучать как "Параметры загрузки доски/задач". Слово "Create" очень смущает тут.

2021-05-17 15:53 UTC, Ensaphelon commented on app/javascript/containers/TaskBoard/TaskBoard.js
> +    const attributes = TaskForm.seialize(params);
seialize -> serialize

2021-05-17 15:53 UTC, Ensaphelon commented on app/javascript/hooks/store/useTasks.js
> +  const loadBoard = () => Promise.all(STATES.map(({ key }) => loadColumn(queryParamsCreate(key))));
1. Параметры загрузки должны передаваться в loadBoard а не являться частью его реализации.
2. key - это стейт задачи или строка, которая его идентифицирует, так и надо его называть

2021-05-18 18:13 UTC, RinatKhabibullin commented on app/javascript/hooks/store/useTasks.js
> +  const loadBoard = () => Promise.all(STATES.map(({ key }) => loadColumn(queryParamsCreate(key))));
1. Не совсем понял замечание, необходимо перенести STATES.map(({ key }) => loadColumn(queryParamsCreate(key))) в отдельную переменную в компонент, а loadBoard переписать так чтобы он принимал на вход массив пропсов и передавал его в Promise.all?
я сделал это таким образом: 
в useTasks.js:
const loadBoard = (boardLoadParams) => Promise.all(boardLoadParams);
в TaskBoard.js:
const boardLoadParams = STATES.map(({ key }) => loadColumn(taskLoadParams(key)));
useEffect(() => loadBoard(boardLoadParams), []);

в итоге у меня почему то useEffect выполняется в бесконечном цикле, не могу найти причину почему, для этого же мы и передаем вторым аргументом пустой массив чтобы так не было.

Подскажи пожалуйста чего я не понимаю, и куда мне копать чтобы разобраться в этом?

2021-05-18 19:15 UTC, RinatKhabibullin commented on app/javascript/hooks/store/useTasks.js
> +  const loadBoard = () => Promise.all(STATES.map(({ key }) => loadColumn(queryParamsCreate(key))));
Вроде бы нашёл решение

2021-05-18 19:40 UTC, Ensaphelon approved these changes

2021-05-18 20:18 UTC, merged