add newrelic
RinatKhabibullin/task-manager pull request #34
Opened 2021-05-27 17:53 UTC by RinatKhabibullin

2021-05-28 17:46 UTC, greybutton requested changes
CI еще падает, я так понял фикс в версии бандлера в прошлом реквесте с роллбаром

2021-05-28 17:46 UTC, greybutton commented on config/newrelic.yml
> +  license_key: 8b375fdbf674ae42cf1736db3cd1e1f450d7NRAL
токены не хранят в коде. сгенерируй новый токен и добавь его через переменные окружения (environment variables)

2021-06-03 19:15 UTC, greybutton approved these changes
аппрув, но добавь здесь использование токена из переменных среды. И желательно новый ключ сделать для ньюрелик и роллбар, которые в гите засветились уже не использовать

2021-06-03 19:15 UTC, greybutton commented on config/newrelic.yml
> +  license_key: 8b375fdbf674ae42cf1736db3cd1e1f450d7NRAL
добавил `NEWRELIC_LICENSE_KEY: ${NEWRELIC_LICENSE_KEY}`, но не используешь)

2021-06-03 20:32 UTC, RinatKhabibullin commented on config/newrelic.yml
> +  license_key: 8b375fdbf674ae42cf1736db3cd1e1f450d7NRAL
Это я просто накосячил, забыл тут использлвать переменную, в .env новый license key

2021-06-04 17:21 UTC, merged